### ISSUE TITLE
Towards 0.8.4

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#114]
- [x] (**Enhancement**) Tweak logic for shuffling in `partition` (MLJ issue #258)

- [x] (**Enhancement**) Make `aggregate(x, measure)` a no-op on scalars `x` (#127)

- [x] (**Bug**) Fix a sign problem in the area under the curve measure, `auc`(#122)

- [x] (**Enhancement**) Add methods `restrict(X, folds, i)`, `corestrict(X, folds, i)` to restrict data to fold or fold complement. Add `complement(folds, i)`, for computing a complement.

- [x] (**Enhancement**) More informative error message for some inappropriate uses of `predict_mode`, `predict_mean` or `predict_median` (#40)
