### ISSUE TITLE
reduce overhead of fit! over update

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#151]
Currently, if one calls fit! on a machine without changing rows, there is an overhead in calls to `selectrows`, calls which are required because the row selection is not cached to the machine and because `selectrows` is slow. The reason `selectrows` is slow is because rows are selected through the Tables.jl interface which does not support random access to rows. 

This is mostly an issue for an iterative model that one is (externally) tracking as the iteration parameter is increased. See [here](Context: https://github.com/alan-turing-institute/MLJ.jl/issues/122#issuecomment-568308065) for context. In the example the slow down is about 2-3 times. 

Since Tables does not support the fast access (although do see the discussion at https://github.com/JuliaData/Tables.jl/issues/123 ) it seems we need to cache (references to) data selections in the machines, and not just previous row indices. For a regular machine this doesn't seem too innocuous, but for nodal machines in a multi-model learning network, this could be limiting for big data sets. Currently learning network nodes do not cache any data. We could make caching optional, but I'm not sure what is the best interface point for this.

**Comment by tlienart** [comment]
Can we locally overload `selectrows` for specific cases where we know the data is in memory? (in particular: `DataFrames`); in some future this may be  resolved upstream but in the mean time that could  be an acceptable solution for the most common scenario?

**Comment by ablaom** [comment]
@tlienart That's a good idea.

**Todo**

- [ ] Overload selectrows for DataFrames
- [ ] Request @jeremiedb for feedback on his benchmarks (see [here](Context: https://github.com/alan-turing-institute/MLJ.jl/issues/122#issuecomment-568308065))
- [ ] Revisit question of caching data

**Comment by ablaom** [comment]
Caching the row refererences is somewhat non-trivial. I think the workaround above suffices for now  and am going to label this as low priority.

**Comment by ablaom** [comment]
Closing in favour of #309
