### ISSUE TITLE
For next minor release (breaking issues)

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#164]
For merging onto `early-march` branch:

- [x] (**breaking**) suppress normalisation of measure weights (PR #208)

- [x] (**breaking**) migrate equality.jl to MLJModelInterface (#178) 

- [x] (**breaking**) Shift the optional `rng` argument of iterator to first position (#215)

**Comment by ablaom** [comment]
Waiting on breaking changes to MLJModelInterface before proceeding with #178
