### ISSUE TITLE
Towards a 0.15 release

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#404]
- [x] (**enhancement**) Add `fitted_params_per_fold` and `report_per_fold` properties to the object returned  by `evaluate`/`evaluate!` to give user access to the outcomes of training for each train/test pair in resampling (#400, https://github.com/alan-turing-institute/MLJ.jl/issues/616)

- [x] (**enhancement**) Implement `logpdf` for `UnivariateFinite` distributions (#411)

- [x] (**code organization**) Remove ScientificTypes as explicit dependency (#403)

- [x] (**bug fix**) Fix bug related to creating new composite models by hand in special case of non-model hyper-parameters (not an issue with `@pipeline` or `@from_network` models). Introduce new `return!` syntax for doing this and  deprecate calling of learning network machines ( #390, #391, #377) 

- [x] (**breaking**) Change the behavior of `evaluate`/`evaluate!` so that weights are only passed to measures if explicitly passed using the key-word argument `weights=...` (#405)

- [x] bump version to 0.15
