### ISSUE TITLE
Towards 0.7.2

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#63]
- [x] (**Enhancement**) Improve show for `UnivariateDistribution` (rounding displayed probabilities) (PR #64)

- [x] (**Bug fix**) Fix problem with averaging `UnivariateFinite` objects all concentrated in single value ([#MLJ290](https://github.com/alan-turing-institute/MLJ.jl/issues/290))

- [x]  (**Bug fix**) If `A` is already a matrix, then `MLJBase.matrix(A, transpose=true)` now actually computes the transpose (#69)

- [x] (**Enhancement**) Make `UnivariateDistribution` constructor more efficient (PR #65 , PR #66)

- [x] Bump to 0.7.2
