### ISSUE TITLE
Towards 0.8.0

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#73]
- [x] (**Enhancement**) Give built-in Ames data sets types with improved scitype interpretations (PR #92)

- [x] (**Enhancement**) Add method `is_same_except_method(m1, m2, exceptions....)` that asks if two `MLJType` objects `m1, m2` have the same field values, with the exception of the field names (symbols) nominated in `exceptions`. 

- [x] (**Enhancement**) Define `Static <: Unsupervised` model subtype and default `fit` for transformers without learned parameters (PR #104, [MLJ #291](https://github.com/alan-turing-institute/MLJ.jl/issues/291))

- [x] (**Enhancement**) Add `confusion_matrix` and the following measures:  `auc`, `accuracy`,
       `balanced_accuracy`,  `matthews_correlation`,  `truepositive`, `truenegative`, `falsepositive`, `falsenegative`,  `truepositive_rate`, `truenegative_rate`, `falsepositive_rate`, `falsenegative_rate`, `falsediscovery_rate`, `negativepredictive_value`, `precision`, plus varied aliases. Do `?measures()` for full list (PR #88)

- [x] (**Enhancement**) Add `aggregate` measure trait and associated `aggregate(v, measures)` method. Anticipating [planned change](https://github.com/alan-turing-institute/MLJ.jl/tree/confmat) to MLJ (PR #88)

- [x] (**Enhancement**) Add `measures()` and `measures(conditions...)` for querying the full list of available models (PR #88)

- [x] (**Enhancement**) Add `roc_curve` to compute the receiver operator characteristic in binary classification (PR #88)

- [x] (**Breaking**) Add `@load` stub (PR #101). Breaks MLJModels which previously owned this method. 

- [x] Add `supports_online` model trait and `update_data` fallback, in preparation for MLJ online learning support (PR #102, [MLJ #60](https://github.com/alan-turing-institute/MLJ.jl/issues/60 ))

**Comment by ablaom** [comment]
Be sure to pull #88 before checking and pulling #101 and #102. That is, follow the order above
