### ISSUE TITLE
Towards 0.7.4

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#80]
- [x]  (**Enhancement**) Enable fitting of `UnivariateFinite` to weighted samples; syntax: `fit(UnivariateFinite, samples, weights)` (PR #81)

- [x] (**Bug fix**) Tweak to definition of "in" for MLJType (#79, [MLJ #320](https://github.com/alan-turing-institute/MLJ.jl/issues/320))

- [x] (**Enhancement**) Remove optional dependency CSV in favour of hard dependency on DelimitedFiles for loading built-in  data sets, to improve load times (#77, #78)
